#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=98

boot_phy_control() {
	if grep -qsw 0 /proc/xiaoqiang/ft_mode; then
		# stop wired phy, avoid getting the upper-level ip address
		/sbin/phyhelper stop
	else
		# if router is in factory, start all wired phy
		/sbin/phyhelper start
	fi
}

boot() {
	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc
	[ -f /proc/net/vlan/config ] && vconfig set_name_type DEV_PLUS_VID_NO_PAD

	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/state
	mkdir -p /var/tmp
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	touch /var/log/wtmp
	touch /var/log/lastlog
	touch /tmp/resolv.conf.auto
	ln -sf /tmp/resolv.conf.auto /tmp/resolv.conf
	grep -q debugfs /proc/filesystems && /bin/mount -o noatime -t debugfs debugfs /sys/kernel/debug
	[ -d /sys/fs/bpf ] && grep -q bpf /proc/filesystems && /bin/mount -o nosuid,nodev,noexec,noatime,mode=0700 -t bpf bpffs /sys/fs/bpf
	[ -d /sys/fs/pstore ] && grep -q pstore /proc/filesystems && /bin/mount -o noatime -t pstore pstore /sys/fs/pstore
	[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

	if [ "$(uci -q get misc.features.detect_delay)" = "1" ]; then
		nice -n -19 /sbin/kmodloader
		echo "wifi detect delay" > /dev/console
	else
		echo "wifi detect normal" > /dev/console

		/sbin/kmodloader

		[ -s /etc/config/wireless ] || {
			# allow wifi modules time to settle
			sleep 1

			/sbin/wifi detect > /tmp/wireless.tmp

			[ -s /tmp/wireless.tmp ] && {
				cat /tmp/wireless.tmp > /etc/config/wireless
			}
			rm -f /tmp/wireless.tmp
		}
	fi

	# temporary hack until configd exists
	/sbin/reload_config

	boot_phy_control
}
