#!/bin/sh /etc/rc.common

START=99
STOP=90

USE_PROCD=1
NAME=meshd
PROG=/usr/sbin/meshd

scan_timewait=10
support_mesh_ver4=$(mesh_cmd support_mesh_version 4)
[ "$support_mesh_ver4" = "1" ] && scan_timewait=5

mesh_iface=$(mesh_cmd mesh_iface)
[ -z "$mesh_iface" ] && mesh_iface="wl0"

start_service() {
	local init_flag=$(uci -q get xiaoqiang.common.INITTED)
	local device=$(uci -q get misc.wireless.if_5G)
	local mac=$(uci -q get wireless.$device.macaddr)
	local meshSupportRE=$(uci -q get misc.features.meshSupportRE)
	if [ -z "$meshSupportRE" ]; then
		meshSupportRE=1
	fi

	if [ "$init_flag" != "YES" ] && [ "$meshSupportRE" == "1" ]; then
		procd_open_instance
		procd_set_param command "$PROG" -i "$mesh_iface" -t $scan_timewait -a $mac
		procd_set_param respawn
		procd_close_instance
	fi
}
