#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
NAME=miwifi-discovery
PROG="/usr/sbin/miwifi-discovery"

start_service() {
    mesh_mode=$(uci -q get xiaoqiang.common.NETMODE)
    mesh_version=$(mesh_cmd max_mesh_version)
    meshSupportRE=$(uci -q get misc.features.meshSupportRE)
    if [ -z "$meshSupportRE" ]; then
        meshSupportRE=1
    fi

    [ "$mesh_mode" == "wifiapmode" ] && exit 0
    [ "$mesh_mode" == "whc_re" -a "$mesh_version" -lt "4" ] && exit 0

    INITTED=$(uci -q get xiaoqiang.common.INITTED)
    [ "$INITTED" != "YES" -a "$meshSupportRE" == "0" ] && exit 0

    if [ "$mesh_version" -ge "4" ]; then
        bh_band=$(mesh_cmd backhaul get real_band)
        mesh_ifname=$(uci -q get misc.backhauls.backhaul_${bh_band}_ap_iface)
        procd_open_instance
        if [ -z "$mesh_mode" ]; then
            # initted default to whc_cap, to support key-mesh
            if [ "$INITTED" = "YES" ]; then
                mesh_mode="whc_cap"
            else
                mesh_mode="whc_re"
            fi
        fi
        procd_set_param command "$PROG" -v "$mesh_version" -i "$mesh_ifname" -m "$mesh_mode"
        procd_set_param respawn
        procd_close_instance
    elif [ "$INITTED" = "YES" ]; then
        procd_open_instance
        procd_set_param command "$PROG"
        procd_set_param respawn
        procd_close_instance
    fi
}
