#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=21

USE_PROCD=1

readonly HTTP_LOCATIONS="/etc/nginx/80-real-locations.conf"

start_service() {
	# start fcgi-cgi first
	procd_open_instance
	procd_set_param command /usr/bin/spawn-fcgi -a 127.0.0.1 -p 8920 -U nobody -F 1 -- /usr/bin/fcgi-cgi
	#procd_set_param file /etc/nginx/nginx.conf
	procd_set_param respawn
	procd_close_instance
	echo "start fcgi-cgi by spawn-fcgi."
	# start nginx
	[ -d /var/log/nginx ] || mkdir -p /var/log/nginx
	[ -d /var/lib/nginx ] || mkdir -p /var/lib/nginx

	init_config

	procd_open_instance
	procd_set_param command /usr/sbin/nginx -c /etc/nginx/nginx.conf -g 'daemon off;'
	procd_set_param file /etc/nginx/nginx.conf
	procd_set_param respawn
	procd_close_instance
	echo "start nginx ok."
}

reload_service() {
	init_config
	nginx -s reload
}

init_config() {
	local _include_file="default-locations.conf"
	local _body_size=$(uci -q get nginx.main.client_max_body_size)

	if [ -n "$_body_size" ]; then
		sed -i "s/client_max_body_size.*$/client_max_body_size ${_body_size};/" \
			/etc/nginx/default-locations.conf
	fi

	if uci -q get nginx.main.force_https|grep -qsx 1; then
		_include_file="force-https-locations.conf"
	fi

	if ! grep -qs "$_include_file" "$HTTP_LOCATIONS"; then
		echo "include '$_include_file';" |tee "$HTTP_LOCATIONS"
	fi
}

