#!/bin/sh

mac=$(getmac wan)
mac_b5=$(echo $mac | cut -d ':' -f 5)
mac_b6=$(echo $mac | cut -d ':' -f 6)
model=$(bdata get model | tr "[A-Z]" "[a-z]")

# Generate default SSID and SSID for uninitialized device
# Extend UID part of default SSID

uid=$mac_b5$mac_b6

bdata set "wl1_ssid=${model}_minet_${uid}"
nvram set "wl1_ssid=${model}_minet_${uid}"
bdata set "wl0_ssid=${model}_minet_${uid}"
nvram set "wl0_ssid=${model}_minet_${uid}"

bdata commit
bdata sync
nvram commit

# SSIDs in wireless config will be updated by wifi detect during next boot
rm -f /etc/config/wireless
sync
