#!/bin/sh
# @Xiaomi crashlog processing script

get_crash_log() {
	cd /tmp || return

	if [ -s /sys/fs/pstore/dmesg-ramoops-0 ]; then
		mv -f /sys/fs/pstore/dmesg-ramoops-0 ./
		tar -czf panic.tar.gz ./dmesg-ramoops-0
		rm -f ./dmesg-ramoops-0
	fi

	# just overwrite old panic logs
	if [ -s /tmp/panic.tar.gz ]; then
		mv -f /tmp/panic.tar.gz /data/usr/log/panic.tar.gz
		sync
	fi
}

upload_crash_log() {
	[ -f /data/usr/log/panic.tar.gz ] || return 0

	mtd_crash_log -u /data/usr/log/panic.tar.gz
	if [ "$?" = "0" ]; then
		logger -p local0.warning -t boot_check "Upload crash done."
		rm -f /data/usr/log/panic.tar.gz
	else
		logger -p local0.warning -t boot_check "Upload crash failed."
	fi
}

[ "$(cat /proc/xiaoqiang/ft_mode)" = "1" ] && return 0

LOCK_UPCRASH="/var/run/upcrash.lock"
trap "lock -u $LOCK_UPCRASH; exit 1" SIGHUP SIGINT SIGTERM
lock -n $LOCK_UPCRASH || return 1

[ "$1" = "upload" ] || get_crash_log

upload_crash_log

lock -u $LOCK_UPCRASH
