#!/bin/sh

[ -f /etc/config/mwan3 ] && {
	[ "$(uci -q get mwan3.wan.track_ip)" = "114.114.114.114 208.67.222.222" ] && uci -q add_list mwan3.wan.track_ip="223.5.5.5"
	[ "$(uci -q get mwan3.wan_2.track_ip)" = "114.114.114.114 208.67.222.222" ] && uci -q add_list mwan3.wan_2.track_ip="223.5.5.5"
	uci commit mwan3
}
