#!/bin/sh /etc/rc.common

START=50
USE_PROCD=1
EXTRA_COMMANDS="off"

off() {
	[ -e "/lib/miwifi/miwifi_core_libs.sh" ] && . /lib/miwifi/miwifi_core_libs.sh;network_accel_hook "restart"
}

start_service() {
	[ -e "/lib/miwifi/miwifi_core_libs.sh" ] && . /lib/miwifi/miwifi_core_libs.sh;network_accel_hook "restart"
}

