#!/bin/sh /etc/rc.common

START=35
STOP=85
USE_PROCD=1


start_service() {
	local mode=$(uci -q get xiaoqiang.common.NETMODE)
	if [ "$mode" = "wifiapmode" -o "$mode" = "lanapmode" -o "$mode" = "whc_re" ]; then
		return 0
	fi

	local status="disabled"
	local sec_list=$(uci show ipv6 | grep "ipv6.wan6[_0-9]*=wan" | awk -F"[.|=]" '{print $2}')
	for sec in $sec_list; do
		local ipv6_mode=$(uci -q get ipv6.$sec.mode)
		[ "$ipv6_mode" != "off" -a "$ipv6_mode" != "passthrough" ] && {
			status="enabled"
			break
		}
	done

	[ "$status" = "disabled" ] && return

	local ra_maxinterval=$(uci -q get dhcp.lan.ra_maxinterval)
	[ -z "$ra_maxinterval" ] && {
		uci -q set dhcp.lan.ra_maxinterval='20'
		uci commit dhcp
	}

	procd_open_instance
	procd_set_param command /usr/sbin/odhcpd
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	procd_send_signal odhcpd
}

service_triggers()
{
	procd_add_reload_trigger "dhcp"
}

