#!/bin/sh

. /lib/functions.sh

readonly RESTORE_DEF_FLAG_FILE="/tmp/restore_defaults_flag"

do_xiaoqiang_defaults() {
	cat /usr/share/xiaoqiang/xiaoqiang-defaults.txt | while read line
	do
		[ -n "$line" ] && nvram set "$line"
	done
}

do_flag_override() {
	local flag="$1"
	local b_val=`bdata get $flag`
	local n_val=`nvram get $flag`
	
	[ "$b_val" = "$n_val" ] && return 0
	[ "$b_val" = "1" ] && nvram set "$flag"=1
}

flag_override() {
	do_flag_override uart_en
	do_flag_override ssh_en
	do_flag_override telnet_en
	do_flag_override boot_wait
}

do_set_default_ssid() {
	local num=`nvram get wl1_ssid | cut -b 8-11`
	local temp=0x"$num"
	local newnum="000"`printf "%x\n" $((0xffff-$temp))`
	local pos=`expr length $newnum - 4`
	local suf="_5G"
	local ssid2G=""
	local result2G=""
	local has5G=""
	local ssid5G=""
	local result5G=""

	newnum=`echo ${newnum:$pos:4} | tr [a-z] [A-Z]`
	ssid2G=`nvram get wl1_ssid`
	result2G=`echo $ssid2G"_"$newnum`
	nvram set wl1_ssid=$result2G

	has5G=`uci get misc.wireless.if_5G 2>/dev/null`
	if [ -n "$has5G" ]; then
		ssid5G=`nvram get wl0_ssid | cut -b -11`
		result5G=`echo ${ssid5G}"_"${newnum}${suf}`
		nvram set wl0_ssid=$result5G
	fi
}

do_bdata_sync(){

	bdata sync

	[ -x /usr/share/xiaoqiang/xiaoqiang-ignore.txt ] && {
		cat /usr/share/xiaoqiang/xiaoqiang-ignore.txt | while read line
		do
			[ -n "$line" ] && nvram unset "$line"
		done
	}
}

set_restore_defaults_flag () {
	touch "$RESTORE_DEF_FLAG_FILE"
}

restore_nvram () {
	local restore=`nvram get restore_defaults`
	local ft_mode=`cat /proc/xiaoqiang/ft_mode`
	local nvram_corrupt=0
	local need_commit=0
	local wl0_val=""
	local wl1_val=""
	local wl2_val=""

	# set restore_defaults flag, erase user config
	if [ "$restore" = "1" ]; then
		local flag_name=`uci get misc.mount_bind_etc.flag_name`
		nvram set $flag_name=1
		mtd erase overlay
		need_commit=1
		set_restore_defaults_flag

		# try to log restore event
		if which sp_log_info.sh >/dev/null; then
			sp_log_info.sh -i -k "sys.reset.manual" -m "1"
		fi
	fi

	if [ "$ft_mode" != "1" ]; then
		local sn=`nvram get SN`
		local wl1_ssid=`nvram get wl1_ssid`
		local countrycode=`nvram get CountryCode`

		if [ -z "$sn" -o -z "$wl1_ssid" -o -z "$countrycode" ]; then
			nvram_corrupt=1
		fi
	fi

	# skip restore wifi radio flag from defaults if factory mode
	if [ "$ft_mode" = "1" ]; then
		wl1_val=`nvram get wl1_radio`
		wl0_val=`nvram get wl0_radio`
		wl2_val=`nvram get wl2_radio`
	fi

	#restore: 1, 恢复出厂设置；2，ota升级
	#nvram_corrupt: 1, nvram被破坏
	if [ "$nvram_corrupt" = "1"  ]; then
		echo "Nvram partition corrupt, restore nvram to default!"
		do_xiaoqiang_defaults
		do_bdata_sync
		need_commit=1
	fi

	# restore to factory setting
	if [ "$restore" = "1" ]; then
		nvram clear /usr/share/xiaoqiang/xiaoqiang-reserved.txt
		do_xiaoqiang_defaults
		do_bdata_sync
		need_commit=1
	fi

	# OTA upgrade
	if [ "$restore" = "2" ]; then
		do_xiaoqiang_defaults
		flag_override
		need_commit=1
	fi

	if [ "$ft_mode" = "1" ]; then
		[  "$wl1_val" != "" -a -n "$wl1_val" ] && {
			nvram set wl1_radio=$wl1_val
			need_commit=1
		}
		[  "$wl0_val" != "" -a -n "$wl0_val" ] && {
			nvram set wl0_radio=$wl0_val
			need_commit=1
		}
		[  "$wl2_val" != "" -a -n "$wl2_val" ] && {
			nvram set wl2_radio=$wl2_val
			need_commit=1
		}
	fi

	local countrycode=`nvram get CountryCode`
	[ "$countrycode" = "EU" ] && {
		nvram set CountryCode=DE
		need_commit=1
	}

	[ "$need_commit" = "1" ] && nvram commit
}

boot_hook_add preinit_main restore_nvram
