#!/bin/sh

iface_guest_2g=$(uci -q get misc.wireless.iface_guest_2g_name)
iface_guest_5g=$(uci -q get misc.wireless.iface_guest_5g_name)
disabled_2_cur="`uci -q get wireless.$iface_guest_2g.disabled`"
disabled_5_cur="`uci -q get wireless.$iface_guest_5g.disabled`"

guest_wifi_down() {
	uci set wireless.$iface_guest_2g.disabled=1
	uci set wireless.$iface_guest_2g.closingTime=0
	uci set wireless.$iface_guest_5g.disabled=1
	uci set wireless.$iface_guest_5g.closingTime=0
	uci commit wireless
	/sbin/wifi update &
	/etc/init.d/guestwifi_separation stop 2>>/dev/null

	uci -q set firewall.guest.enabled='0'
	uci commit firewall
	/usr/sbin/sysapi guest clean &
}

guest_wifi_up() {
	uci set wireless.$iface_guest_2g.disabled=0
	uci set wireless.$iface_guest_5g.disabled=0
	uci commit wireless
	/sbin/wifi update &
	/etc/init.d/guestwifi_separation restart 2>>/dev/null

	uci -q set firewall.guest.enabled='1'
	uci commit firewall
	/usr/sbin/sysapi guest set &
}

case "$1" in
	down) guest_wifi_down;;
	up) guest_wifi_up;;
esac
