#!/bin/sh

g_i2c_dev_idx=0
g_nxp_i2c_bus_address=0x54
g_nxp_cap_container="0xe1 0x43 0x80 0x09"

g_fm_i2c_bus_address=57
g_fm_cap_container="0xe1 0x10 0x6d 0x00"

show_usage() {
	cat <<EOF
usage:
	nfc init
	nfc disable
	nfc rm_wifi
	nfc update [ndef_msg] [msg_len]
EOF
	exit 1
}

nxp_i2c_init() {
	local cmd_str=""
	g_i2c_dev_idx=`i2cdetect -l | awk '{print $1}' | awk -F '-' '{print $2}'`
	g_i2c_bus_address=`i2cdetect -y -r "$g_i2c_dev_idx" | awk '{if (NR>1){print $0}}' | cut -d " " -f 2- | tr -cd "[0-9]"`

	local cap_container=`i2ctransfer -y "$g_i2c_dev_idx" w2@0x"$g_i2c_bus_address" 0x00 0x00 r4`

	if [ "$cap_container" != "$g_nxp_cap_container" ]
	then
		cmd_str="w6@0x""$g_i2c_bus_address"" 0x00 0x00 ""$g_nxp_cap_container"
		i2ctransfer -y "$g_i2c_dev_idx" $cmd_str
	fi
}

fm_i2c_init() {
	return
}
nxp_i2c_disable() {
	local cmd_str=""
	g_i2c_dev_idx=`i2cdetect -l | awk '{print $1}' | awk -F '-' '{print $2}'`
	g_i2c_bus_address=`i2cdetect -y -r "$g_i2c_dev_idx" | awk '{if (NR>1){print $0}}' | cut -d " " -f 2- | tr -cd "[0-9]"`

	cmd_str="w6@0x""$g_i2c_bus_address"" 0x00 0x01 0x00 0x00 0x00 0x00"
	i2ctransfer -y "$g_i2c_dev_idx" $cmd_str
}

fm_i2c_disable() {
	local cmd_str=""
	g_i2c_dev_idx=`i2cdetect -l | awk '{print $1}' | awk -F '-' '{print $2}'`
	g_i2c_bus_address=`i2cdetect -y -r "$g_i2c_dev_idx" | awk '{if (NR>1){print $0}}' | cut -d " " -f 2- | tr -cd "[0-9]"`

	cmd_str="w6@0x""$g_i2c_bus_address"" 0x00 0x10 0x00 0x00 0x00 0x00"
	i2ctransfer -y "$g_i2c_dev_idx" $cmd_str
}

nxp_i2c_update() {
	g_i2c_dev_idx=`i2cdetect -l | awk '{print $1}' | awk -F '-' '{print $2}'`
	g_i2c_bus_address=`i2cdetect -y -r "$g_i2c_dev_idx" | awk '{if (NR>1){print $0}}' | cut -d " " -f 2- | tr -cd "[0-9]"`

	local count=0
	while [ $count -le 3 ]; do
		local cmd_str=""
		local addr_str=""
		local value_str=""
		local pad_str=""
		local ndef_str=$2
		local s_pos=0
		local s_len=19
		local write_len=$3
		local ndef_len=$3
		local ndef_start_addr=0x0001
		local eep_str=""

		cmd_str="w2@0x""$g_i2c_bus_address"" 0x00 0x01"" r""$ndef_len"
		eep_str=`i2ctransfer -y "$g_i2c_dev_idx" $cmd_str`

		if [ "$ndef_str" = "$eep_str" ]; then
			return
		fi

		while [ $write_len -gt 3 ];
		do
			addr_str=$(printf "0x%02x 0x%02x" $(($ndef_start_addr>>8)) $(($ndef_start_addr&0xff)))
			value_str="${ndef_str:$s_pos:$s_len}"
			cmd_str="w6@0x""$g_i2c_bus_address"" $addr_str"" $value_str"
			write_len=$(($write_len - 4))
			ndef_start_addr=$(($ndef_start_addr + 1))
			s_pos=$(($s_pos + 20))
			i2ctransfer -y "$g_i2c_dev_idx" $cmd_str
			usleep 10000
		done

		if [ $write_len -gt 0 ];then
			if [ $write_len -gt 2 ];then
				pad_str="0x00"
			elif [ $write_len -gt 1 ];then
				pad_str="0x00 0x00"
			elif [ $write_len -gt 0 ];then
				pad_str="0x00 0x00 0x00"
			fi
			value_str="${ndef_str:$s_pos}"
			addr_str=$(printf "0x%02x 0x%02x" $(($ndef_start_addr>>8)) $(($ndef_start_addr&0xff)))
			cmd_str="w6@0x""$g_i2c_bus_address"" $addr_str"" $value_str"" ""$pad_str"
			i2ctransfer -y "$g_i2c_dev_idx" $cmd_str
		fi
		sleep $count
		let "count++"
	done

}

fm_i2c_update() {
	g_i2c_dev_idx=`i2cdetect -l | awk '{print $1}' | awk -F '-' '{print $2}'`
	g_i2c_bus_address=`i2cdetect -y -r "$g_i2c_dev_idx" | awk '{if (NR>1){print $0}}' | cut -d " " -f 2- | tr -cd "[0-9]"`

	local count=0
	while [ $count -le 3 ]; do
		local cmd_str=""
		local addr_str=""
		local value_str=""
		local pad_str=""
		local ndef_str=$2
		local s_pos=0
		local s_len=19
		local write_len=$3
		local ndef_len=$3
		local ndef_start_addr=0x0010
		local eep_str=""

		cmd_str="w2@0x""$g_i2c_bus_address"" 0x00 0x10"" r""$ndef_len"
		eep_str=`i2ctransfer -y "$g_i2c_dev_idx" $cmd_str`

		if [ "$ndef_str" = "$eep_str" ]; then
			return
		fi

		while [ $write_len -gt 3 ];
		do
			addr_str=$(printf "0x%02x 0x%02x" $(($ndef_start_addr>>8)) $(($ndef_start_addr&0xff)))
			value_str="${ndef_str:$s_pos:$s_len}"
			cmd_str="w6@0x""$g_i2c_bus_address"" $addr_str"" $value_str"
			write_len=$(($write_len - 4))
			ndef_start_addr=$(($ndef_start_addr + 4))
			s_pos=$(($s_pos + 20))
			i2ctransfer -y "$g_i2c_dev_idx" $cmd_str
			usleep 10000
		done

		if [ $write_len -gt 0 ];then
			if [ $write_len -gt 2 ];then
				pad_str="0x00"
			elif [ $write_len -gt 1 ];then
				pad_str="0x00 0x00"
			elif [ $write_len -gt 0 ];then
				pad_str="0x00 0x00 0x00"
			fi
			value_str="${ndef_str:$s_pos}"
			addr_str=$(printf "0x%02x 0x%02x" $(($ndef_start_addr>>8)) $(($ndef_start_addr&0xff)))
			cmd_str="w6@0x""$g_i2c_bus_address"" $addr_str"" $value_str"" ""$pad_str"
			i2ctransfer -y "$g_i2c_dev_idx" $cmd_str
		fi
		sleep $count
		let "count++"
	done

}

rm_nfc_wifi()
{
	local nfc_default_cfg=$(uci -q get wireless.nfc_2g.ifname)
	if [ -n "$nfc_default_cfg" ]; then
		uci del wireless.nfc_2g
		uci del wireless.nfc_5g
		uci commit
	fi
}

case $1 in
	init) fm_i2c_init ;;
	update) fm_i2c_update "$@";;
	disable) fm_i2c_disable ;;
	rm_wifi) rm_nfc_wifi;;
	*) show_usage ;;
esac
